### PR TITLE
Customer Registration Added with Backend

### PR DESCRIPTION
**Pull request by Barun-7**
manager login integrated with backend

### CODE REVIEW

**Comment by priyadarshishubh** [comment]
Accepted Manager Login with Backend Integrated

**Comment by Barun-7** [comment]
Manager integrated with backend

**Comment by Barun-7** [comment]
Manager integrated with backend

**Comment by Barun-7** [comment]
Manager integrated with backend

**Comment by priyadarshishubh** [comment]
Commit Manager Login

**Pull request merged**
